import re


def replace(actual_name):
    actual_name1 = actual_name.replace('DONAR', "")
    actual_name1 = actual_name1.replace('DRIVER', "")
    actual_name1 = actual_name1.replace('LICENSE', "")
    actual_name1 = actual_name1.replace('FOR', "")

    actual_name1 = actual_name1.replace('SIGNATURE', "")
    actual_name1 = actual_name1.replace('ESTABČISHED', "")
    actual_name1 = actual_name1.replace('ESTABLISHED', "")
    actual_name1 = actual_name1.replace('Established', "")
    actual_name1 = actual_name1.replace('Iss', "")
    actual_name1 = actual_name1.replace('iss', "")
    actual_name1 = actual_name1.replace('Doe', "")
    actual_name1 = actual_name1.replace('LICENSED', "")
    actual_name1 = actual_name1.replace(' I ', "")
    actual_name1 = actual_name1.replace('REPLACEDOS', "")
    # actual_name1 = actual_name1.replace('ENO ', "")
    actual_name1 = actual_name1.replace('END ', "")
    # actual_name1 = actual_name1.replace('DO ', "")
    actual_name1 = actual_name1.replace(' Les ', "")
    actual_name1 = actual_name1.replace(' CLASSE ', "")
    actual_name1 = actual_name1.replace('Signature', "")
    actual_name1 = actual_name1.replace('signature', "")
    actual_name1 = actual_name1.replace('For', "")
    actual_name1 = actual_name1.replace('FOR', "")
    actual_name1 = actual_name1.replace('for', "")
    actual_name1 = actual_name1.replace('SIGNATURE', "")
    actual_name1 = actual_name1.replace('JERSEY ', "")
    actual_name1 = actual_name1.replace('aai ', "")
    actual_name1 = actual_name1.replace('COMMERCIAL', "")
    actual_name1 = actual_name1.replace(' CIPTA', "")
    actual_name1 = actual_name1.replace('E R B', "")
    actual_name1 = actual_name1.replace('CLASE', "")
    actual_name1 = actual_name1.replace('LUCENSEo', "")
    actual_name1 = actual_name1.replace('FERRER', "")
    actual_name1 = actual_name1.replace('CLASS A', "")
    actual_name1 = actual_name1.replace('Cam ', "")
    actual_name1 = actual_name1.replace('YORK', "")
    actual_name1 = actual_name1.replace('NEWJERSE', "")
    actual_name1 = actual_name1.replace('USA ', "")
    actual_name1 = actual_name1.replace('Blocked ', "")
    actual_name1 = actual_name1.replace('STATE', "")
    actual_name1 = actual_name1.replace(' AC', "")
    actual_name1 = actual_name1.replace('CLASS A', "")
    actual_name1 = actual_name1.replace('Can ', "")
    actual_name1 = actual_name1.replace(' K ', " ")
    actual_name1 = actual_name1.replace('class A', "")
    actual_name1 = actual_name1.replace('CLASS B', "")
    actual_name1 = actual_name1.replace('CLASS B', "")
    actual_name1 = actual_name1.replace('class B', "")
    actual_name1 = actual_name1.replace('CLASS E', "")
    actual_name1 = actual_name1.replace('CLASS E', "")
    actual_name1 = actual_name1.replace('class E', "")
    actual_name1 = actual_name1.replace('CLASS F', "")
    actual_name1 = actual_name1.replace('CLASS F', "")
    actual_name1 = actual_name1.replace('class F', "")
    actual_name1 = actual_name1.replace('CLASSC', "")
    actual_name1 = actual_name1.replace('CEXP', "")
    actual_name1 = actual_name1.replace(' BE ', " ")
    actual_name1 = actual_name1.replace('KAROLA', "")
    actual_name1 = actual_name1.replace('B-', "")
    actual_name1 = actual_name1.replace('Exo', "")
    actual_name1 = actual_name1.replace(' IMWHS ', "")
    actual_name1 = actual_name1.replace('MEmp', "")
    actual_name1 = actual_name1.replace('Notes', "")
    actual_name1 = actual_name1.replace(' OLI ', "")
    actual_name1 = actual_name1.replace('Vlas', "")
    actual_name1 = actual_name1.replace('Exp', "")
    actual_name1 = actual_name1.replace('LICENCE', "")
    actual_name1 = actual_name1.replace('bentu', "")
    actual_name1 = actual_name1.replace('ORGAN', "")
    actual_name1 = actual_name1.replace('nacrtaa', "")
    actual_name1 = actual_name1.replace('ATION ', "")
    actual_name1 = actual_name1.replace('SRSEY ', "")
    actual_name1 = actual_name1.replace('RUOSEPH', "JOSEPH")
    actual_name1 = actual_name1.replace('IUOSEPH', "JOSEPH")
    actual_name1 = actual_name1.replace('OONOR ', "")
    actual_name1 = actual_name1.replace('Taxes ', "")
    actual_name1 = actual_name1.replace('Tax ', "")
    actual_name1 = actual_name1.replace('TAX ', "")
    actual_name1 = actual_name1.replace('TAXES ', "")
    actual_name1 = actual_name1.replace('ires ', "")
    actual_name1 = actual_name1.replace('Dups', "")
    actual_name1 = actual_name1.replace('Neder', "")
    actual_name1 = actual_name1.replace('dass', "")
    actual_name1 = actual_name1.replace('AOhio', "")
    actual_name1 = actual_name1.replace('OD. ', "")
    actual_name1 = actual_name1.replace('DRIVER', "")
    actual_name1 = actual_name1.replace(' EXL', "GU")
    actual_name1 = actual_name1.replace(':', "")
    actual_name1 = actual_name1.replace('JTD', "")
    actual_name1 = actual_name1.replace('LICENSE', "")
    actual_name1 = actual_name1.replace('License', "")
    actual_name1 = actual_name1.replace('Null', "")
    actual_name1 = actual_name1.replace(' USA ', "")
    actual_name1 = actual_name1.replace('EYES', "")
    actual_name1 = actual_name1.replace('PAYTOTHE ', "")
    actual_name1 = actual_name1.replace(' TO ', "")
    actual_name1 = actual_name1.replace('THE ', "")
    actual_name1 = actual_name1.replace('ORDER', "")
    actual_name1 = actual_name1.replace(' No ', "")
    actual_name1 = actual_name1.replace('Payro', "")
    actual_name1 = actual_name1.replace(' OC ', "")
    actual_name1 = actual_name1.replace(' OF ', "")
    actual_name1 = actual_name1.replace(' LN', "")
    actual_name1 = actual_name1.replace(' EN ', "")
    actual_name1 = actual_name1.replace(' AP ', "")
    actual_name1 = actual_name1.replace('Expires', "")
    actual_name1 = actual_name1.replace('Name', "")
    actual_name1 = actual_name1.replace('DENONE', "")
    actual_name1 = actual_name1.replace('NONE', "")
    actual_name1 = actual_name1.replace('Address', "")
    actual_name1 = actual_name1.replace('CLASS D', "")
    actual_name1 = actual_name1.replace('CLASS', "")
    actual_name1 = actual_name1.replace('CLASSE', "")
    actual_name1 = actual_name1.replace('CLASEXP', "")
    actual_name1 = actual_name1.replace('EXP', "")
    actual_name1 = actual_name1.replace('ISS', "")
    actual_name1 = actual_name1.replace('SExr', "")
    actual_name1 = actual_name1.replace('Payroll', "")
    actual_name1 = actual_name1.replace('Attn', "")
    actual_name1 = actual_name1.replace('GEXP', "")
    actual_name1 = actual_name1.replace('Class D', "")
    actual_name1 = actual_name1.replace('Class', "")
    actual_name1 = actual_name1.replace('class D', "")
    actual_name1 = actual_name1.replace('class C', "")
    actual_name1 = actual_name1.replace('class', "")
    actual_name1 = actual_name1.replace(' DM ', "")
    actual_name1 = actual_name1.replace('Height', "")
    actual_name1 = actual_name1.replace('Expires', "")
    actual_name1 = actual_name1.replace('Expiros', "")
    actual_name1 = actual_name1.replace('Expires', "")
    actual_name1 = actual_name1.replace(' arark ', "")
    actual_name1 = actual_name1.replace(' VA ', "")
    actual_name1 = actual_name1.replace('Name', "")
    actual_name1 = actual_name1.replace('NOWY', "")
    actual_name1 = actual_name1.replace('DENONE', "")
    actual_name1 = actual_name1.replace('NONE', "")
    actual_name1 = actual_name1.replace('JERSEYUTO', "")
    actual_name1 = actual_name1.replace('DIVERSENSE', "")
    actual_name1 = actual_name1.replace('nnFOR', "")
    actual_name1 = actual_name1.replace('vehicle', "")
    actual_name1 = actual_name1.replace('JERSEYFeater', "")
    actual_name1 = actual_name1.replace('NEW ', "")
    actual_name1 = actual_name1.replace('Address', "")
    actual_name1 = actual_name1.replace('CGFINANCING', "")
    actual_name1 = actual_name1.replace('Motor', "")
    actual_name1 = actual_name1.replace('driver', "")
    actual_name1 = actual_name1.replace('Driver', "")
    actual_name1 = actual_name1.replace('Moncler', "")
    actual_name1 = actual_name1.replace('CLASS D', "")
    actual_name1 = actual_name1.replace('CLASS C', "")
    actual_name1 = actual_name1.replace('CLASS', "")
    actual_name1 = actual_name1.replace('CLASSE', "")
    actual_name1 = actual_name1.replace('CLASEXP', "")
    actual_name1 = actual_name1.replace('EXP', "")
    actual_name1 = actual_name1.replace('Cass D', "")
    actual_name1 = actual_name1.replace('Cass', "")
    actual_name1 = actual_name1.replace(' ISS ', "")
    actual_name1 = actual_name1.replace('SExr', "")
    actual_name1 = actual_name1.replace('GEXP', "")
    actual_name1 = actual_name1.replace('ORGAN', "")
    actual_name1 = actual_name1.replace('DONOR', "")
    actual_name1 = actual_name1.replace('DONORJawa', "")
    actual_name1 = actual_name1.replace('DOB', "")
    actual_name1 = actual_name1.replace('ub', "")
    actual_name1 = actual_name1.replace('Cit', "")
    actual_name1 = actual_name1.replace('exp ', "")
    actual_name1 = actual_name1.replace('=', " ")
    actual_name1 = actual_name1.replace(',', " ")
    actual_name1 = actual_name1.replace('@', " ")
    actual_name1 = actual_name1.replace('#', " ")
    actual_name1 = actual_name1.replace('%', " ")
    actual_name1 = actual_name1.replace('class', "")
    actual_name1 = actual_name1.replace('^', " ")
    actual_name1 = actual_name1.replace('CGA', "")
    actual_name1 = actual_name1.replace('CONG', "")
    actual_name1 = actual_name1.replace('identifier', "")
    actual_name1 = actual_name1.replace('EENHANCED', "")
    actual_name1 = actual_name1.replace(' am ', "")
    actual_name1 = actual_name1.replace(' Mal ', "")
    actual_name1 = actual_name1.replace(' OL ', "")
    actual_name1 = actual_name1.replace('GIN ', "")
    actual_name1 = actual_name1.replace('CASS', "")
    actual_name1 = actual_name1.replace('ADP ', "")
    actual_name1 = actual_name1.replace('CITY', "")
    actual_name1 = actual_name1.replace(' SU ', "")
    actual_name1 = actual_name1.replace('MWAberty', "")
    actual_name1 = actual_name1.replace('FILE', "")
    actual_name1 = actual_name1.replace('WILLIAMS RICHARD NI', "WILLIAMS RICHARD J")
    actual_name1 = actual_name1.replace('Beginning', "")
    actual_name1 = actual_name1.replace('Beginning', "")
    actual_name1 = actual_name1.replace('igs', "")
    actual_name1 = actual_name1.replace('exo ', "")
    actual_name1 = actual_name1.replace('Statement', "")
    actual_name1 = actual_name1.replace('Single', "")
    actual_name1 = actual_name1.replace('Exemptions', "")
    actual_name1 = actual_name1.replace('Parasti', "")
    # actual_name1 = actual_name1.replace('JR', " ")
    actual_name1 = actual_name1.replace(' LAN', "L")
    # actual_name1 = actual_name1.replace('NG ', "")
    actual_name1 = actual_name1.replace(' ICE', "")
    actual_name1 = actual_name1.replace('Prestas', "")
    actual_name1 = actual_name1.replace('Ss ', "")
    actual_name1 = actual_name1.replace('NOIR ', " D ")
    actual_name1 = actual_name1.replace('ss ', "")
    actual_name1 = actual_name1.replace('EX-', "")
    actual_name1 = actual_name1.replace('E-', "")
    actual_name1 = actual_name1.replace('xe ', " ")
    actual_name1 = actual_name1.replace('SBE C', "")
    actual_name1 = actual_name1.replace('EX ', "")
    actual_name1 = actual_name1.replace('Ex ', "")
    actual_name1 = actual_name1.replace('Ex ', "")
    actual_name1 = actual_name1.replace('owances', "")
    actual_name1 = actual_name1.replace(' DRI', "DR")
    actual_name1 = actual_name1.replace('Issued', "")
    actual_name1 = actual_name1.replace('Iss ', "")
    actual_name1 = actual_name1.replace('HS ', "")
    actual_name1 = actual_name1.replace('EARLENE MICHELLEPUIG ', "SHAEARLENE MICHELLE PUIG")
    actual_name1 = actual_name1.replace('Maso', "")
    actual_name1 = actual_name1.replace(' EER ', "")
    actual_name1 = actual_name1.replace('Federa', "")
    actual_name1 = actual_name1.replace(' NY ', "")
    actual_name1 = actual_name1.replace(' UN ', "")
    actual_name1 = actual_name1.replace('Exr ', "")
    # actual_name1 = actual_name1.replace('Is ', "")
    actual_name1 = actual_name1.replace('un ', "")

    actual_name1 = re.sub(r"\b(!?es |iss |er |or |EN |EXP|HGT|Is |Earnings|Donor |AP |=|,|@|#|%|^|CGA| ER |CONG|EENHANCED|am|Mal| OL |GIN|CASS C |D |AD | SU |MWAberty|FILE|Beginning|Statement|ll|l |JTD|LICENSE| USA |EYES|DXP|FN|PAYTOTHE |DiP|DIP| IS | TO |THE |ORDER|No |Payro| OC | OF | LN | ADP |Expires|Name|DENONE|NONE|Address|CLASSE|CLASEXP|ISS|SExr|Payroll|Attn|GEXP|class|Class| DM |Height|Expiros|Cass|CLASS|ClassE|ORGAN|DONORJawa|DOB|ub|CD)",
        "",actual_name1)
    # actual_name1 = re.sub(
    #     r"\s(=?EXP|HGT|Earnings|Donor|AP |=|,|@|#|%|^|ER |CGA|CONG|EENHANCED|am|Mal| OL |GIN|CASS|C |D | AD | SU |MWAberty|FILE|Beginning|Statement|ll|l |JTD|LICENSE|USA |EYES|DXP|FN|PAYTOTHE|DiP|DIP|IS | TO |THE |ORDER|No |Payro| OC | OF |LN |EN |ADP |Expires|Name|DENONE|NONE|Address|CLASSE|CLASEXP|EXP|ISS|SExr|Payroll|Attn|GEXP|Class|DM |Height|Expiros|Cass|CLASS|ClassE|ORGAN|DONORJawa|DOB|ub|CD)\b",
    #     "", actual_name1)
    return actual_name1

def address_replace(value):
    value = value.replace('BLACKWG00', 'BLACKWOOD')
    value = value.replace('BLACKW000', 'BLACKWOOD')


    value = value.replace('FILE', '')
    value = value.replace(' | ', ' ')
    value = value.replace('BLACKWOOO', 'BLACKWOOD')
    value = value.replace('BLACKWOOQ', 'BLACKWOOD')
    if re.search(
            r'(\s?\d+\s([A-Za-z]+)?\s?([A-Za-z]+)?\s?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?[#.,/]?\s?(\w*)?\s?\.?\s?(!?NLNo))\b',
            value):
        value = value.replace('NLNo', 'NJ ')
    if re.search('(!?AŽ|AŻ)', value):
        value = value.replace(re.findall('(!?AŽ|AŻ)', value)[0], "AZ")
    if 'NU ' in value:
        value = value.replace('NU ', 'NJ ')
    elif re.search(
            r'(\s?\d+\s([A-Za-z]+)?\s?([A-Za-z]+)?\s?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?[#.,/]?\s?(\w*)?\s?\.?\s?|[A-Za-z]\s?(!?\.?NL))\b',
            value):
        value = value.replace('.NL', ' NJ ')
        value = value.replace('NL', 'NJ ')
    elif re.search(
            r'(\s?\d+\s([A-Za-z]+)?\s?([A-Za-z]+)?\s?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?[#.,/]?\s?(\w*)?\s?\.?\s?|[A-Za-z]\s?(!?M))\b',
            value):
        value = value.replace('M.', ' NJ ')


    if re.search(
            r'(\s?\d+\s([A-Za-z]+)?\s?([A-Za-z]+)?\s?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?[#.,/]?\s?(\w*)?\s?\.?\s?(!?N\.))\b',
            value):
        value = value.replace('N. ', 'NJ ')

    if ' NJI ' in value:
        value = value.replace('NJI ', 'NJ ')
    if re.search(
            r'(\s?\d+\s([A-Za-z]+)?\s?([A-Za-z]+)?\s?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?[#.,/]?\s?(\w*)?\s?\.?\s?(!? NO))\b',
            value):
        value = value.replace('NO', 'NJ ')
    if ' SU ' in value:
        value = value.replace('SU', 'NJ ')
    if '$' in value:
        value = value.replace('$', '6')
    if re.search(
            r'(\s?\d+\s([A-Za-z]+)?\s?([A-Za-z]+)?\s?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?[#.,/]?\s?(\w*)?\s?\.?\s?(!?MAJ))\b',
            value):
        value = value.replace('MAJ', ' NJ ')
    if re.search(
            r'(\s?\d+\s([A-Za-z]+)?\s?([A-Za-z]+)?\s?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?[#.,/]?\s?(\w*)?\s?\.?\s?(!?AJ))\b',
            value):
        value = value.replace('AJ', ' NJ ')

    if ' NA ' in value:
        value = value.replace('NA', 'NJ ')
    if ' Na ' in value:
        value = value.replace('Na', 'NJ ')
    if ' NW ' in value:
        value = value.replace('NW', 'NJ ')
    if re.search(
            r'(\s?\d+\s([A-Za-z]+)?\s?([A-Za-z]+)?\s?\s?([A-Za-z]+)?\s?(\d+)?\s?([A-Za-z]+)?\s?[#.,/]?(\d+)?\s?([A-Za-z]+)?\s?[#.,/]?\s?(\w*)?\s?\,?\.?\s?(!?NI|NIIN))\b',
            value):

        value = value.replace('NIIN', 'NJ ')
        value = value.replace('NI', 'NJ ')


    print(value)
    return value

def name_replace(text_value,date,zip_code,text_val):
    text_value = text_value.replace(' ExP ', " ")
    text_value = text_value.replace(' DANONE ', " ")
    text_value = text_value.replace('DRIVER', " ")
    text_value = text_value.replace('EXPRES', " ")
    text_value = text_value.replace('Expres', " ")
    text_value = text_value.replace('LICENSE', " ")
    text_value = text_value.replace('KMAL ', " ")
    text_value = text_value.replace('ORGAN DONOR', " ")

    text_value = text_value.replace(' EX ', " ")
    text_value = text_value.replace(' ! ', " ")
    text_value = text_value.replace(' LN ', " ")
    text_value = text_value.replace('FN ', " ")
    text_value = text_value.replace(' CLAss D ', " ")
    text_value = text_value.replace(' EXF ', " ")
    text_value = text_value.replace(' 2 ', " ",1)
    text_value = text_value.replace(' 2', " ",1)
    text_value = text_value.replace('2', " ",1)
    # text_value = text_value.replace('2 ', " ",1)
    text_value = text_value.replace(' CLAss ', " ")
    text_value = text_value.replace(' Imal ', " ")
    text_value = text_value.replace(' po ', " ")
    text_value = text_value.replace(' poB ', " ")
    text_value = text_value.replace(' RESTR ', " ")
    text_value = text_value.replace('Issued', " ")
    text_value = text_value.replace('NEW   JERSEY    AMD  Motor AUTO   DRIVER  LICENSEDL', " ")
    text_value = text_value.replace(' DOB ', " ")
    if re.search(r'\b(!?\d+LOL\s?)',text_value):
        text_value = text_value.replace('LOL', "")
    else:
        text_value = text_value.replace(' LOL ', "")
    text_value = text_value.replace(' ENO ', "")
    text_value = text_value.replace(' Da ', "")
    text_value = text_value.replace(' toe ', "")
    text_value = text_value.replace(' EXP ', " ")
    text_value = text_value.replace(' D08 ', " ")
    # text_value = text_value.replace(' D08 ', " ")
    text_value = text_value.replace(' Dos ', " ")
    text_value = text_value.replace('Commission', " ")
    text_value = text_value.replace('Health', " ")
    text_value = text_value.replace(' oos ', " ")
    text_value = text_value.replace(' Exer ', " ")
    text_value = text_value.replace(' Exe ', " ")
    text_value = text_value.replace('Vehicle', " ")
    text_value = text_value.replace('NEWJERSEY', " ")
    text_value = text_value.replace(' IOWA ', " ")
    text_value = text_value.replace('USA ', " ")
    text_value = text_value.replace('4000EEF01', " ")
    text_value = text_value.replace('「', " ")
    text_value = text_value.replace('«', " ")
    text_value = text_value.replace('«', " ")
    text_value = text_value.replace('|', " ")
    text_value = text_value.replace('Pennsylvania', " ")
    text_value = text_value.replace('_', " ")
    text_value = text_value.replace('(', " ")
    text_value = text_value.replace('080', "")
    text_value = text_value.replace("DRIVER'S LICENSE II", "")
    text_value = text_value.replace(')', " ")
    text_value = text_value.replace('Mat ', "")
    text_value = text_value.replace('REVERSE ', "")
    text_value = text_value.replace('Customer ', "")
    # text_value = text_value.replace(' S ', "")
    text_value = text_value.replace('*', " ")
    text_value = text_value.replace(' Dob ', " ")
    text_value = text_value.replace(' names ', " ")
    # text_value = text_value.replace(' NEW JERSEY NEW JERSEY AUTO DRIVER LICENSED ', " ")
    text_value = text_value.replace(',', " ")
    text_value = text_value.replace(' Given ', " ")
    text_value = text_value.replace(' Family ', " ")
    text_value = text_value.replace(' name ', " ")
    text_value = text_value.replace(' Names ', " ")
    text_value = text_value.replace(' D . O . B . ', " ")
    text_value = text_value.replace(' Name ', " ")
    text_value = text_value.replace(' Address ', " ")
    text_value = text_value.replace(' dob ', " ")
    text_value = text_value.replace(' CLASSD ', " ")
    text_value = text_value.replace(' C3 ', " ")
    text_value = text_value.replace(' CLASS D ', " ")
    text_value = text_value.replace(' Class D ', " ")
    text_value = text_value.replace(' Ex ', " ")
    text_value = text_value.replace(' ex ', " ")
    text_value = text_value.replace(' a ', "")

    val = date.split(",")
    avoid_signature=''
    for i in range(len(val)):
        text_value = text_value.replace(val[i], "")
    if re.search(r'(!?GA|PA)', zip_code):
        if re.search(r"(!?Expires:|EXP|Expires|Exp|Expiros|EXPIRES|EXPIROS|EER)", text_val):
            avoid_signature = ' '.join(map(str, text_val.split(re.findall(r"(!?Expires:|EXP|Expires|Exp|Expiros|EXPIRES|EXPIROS|EER)", text_val)[0], 1)[1].split()[
                                                                  0:1]))
            for i in range(len(val)):
                avoid_signature = avoid_signature.replace(val[i], "")
    # if re.search('(!?NV|OH|TX|WA|CT|MA|NC|CO|DE|ID|IN|KS|ME|MS|MT|NE|NH|ND|SD|UT|VT|WI)', zip_code):
    #     if re.search(r'\b\s?(!?8|2)\s?(\d+)?\b', text_value):
    #         text_value = text_value.replace(' 8', ' ')
    #         # text_value = text_value.split('2', 1)[1]
    value = text_value.replace(":", "")
    # print("in replace",value)
    return value,avoid_signature

def paystub_replace(actual_name):
    # actual_name=actual_name.replace('NY',"")
    actual_name=actual_name.replace(' HDV',"")
    actual_name=actual_name.replace('Additional',"")
    actual_name=actual_name.replace('Taxes',"")
    actual_name=actual_name.replace('Tax',"")
    actual_name=actual_name.replace('',"")
    return actual_name


