import re


def replace(actual_name1):
    actual_name = actual_name1.replace('DONAR', "")
    actual_name = actual_name.replace('Notes', "")
    actual_name = actual_name.replace('OLI', "")
    actual_name = actual_name.replace('Vlas', "")
    actual_name = actual_name.replace('Exp', "")
    actual_name = actual_name.replace('LICENCE', "")
    actual_name = actual_name.replace('bentu', "")
    actual_name = actual_name.replace('ORGAN', "")
    actual_name = actual_name.replace('nacrtaa', "")
    actual_name = actual_name.replace('RUOSEPH', "JOSEPH")
    actual_name = actual_name.replace('IUOSEPH', "JOSEPH")
    actual_name = actual_name.replace('OONOR', "")
    actual_name = actual_name.replace('ires', "")
    actual_name = actual_name.replace('Dups', "")
    actual_name = actual_name.replace('Neder', "")
    actual_name = actual_name.replace('AOhio', "")
    actual_name = actual_name.replace('OD.', "")
    actual_name = actual_name.replace('DRIVER', "")
    actual_name = actual_name.replace(' EXL', "GU")
    actual_name = actual_name.replace(':', "")
    actual_name = actual_name.replace('JTD', "")
    actual_name = actual_name.replace('LICENSE', "")
    actual_name = actual_name.replace('License', "")
    actual_name = actual_name.replace('Null', "")
    actual_name = actual_name.replace(' USA ', "")
    actual_name = actual_name.replace('EYES', "")
    actual_name = actual_name.replace('PAYTOTHE', "")
    actual_name = actual_name.replace(' TO ', "")
    actual_name = actual_name.replace('THE', "")
    actual_name = actual_name.replace('ORDER', "")
    actual_name = actual_name.replace('No', "")
    actual_name = actual_name.replace('Payro', "")
    actual_name = actual_name.replace('OC', "")
    actual_name = actual_name.replace('OF', "")
    actual_name = actual_name.replace('LN', "")
    actual_name = actual_name.replace(' EN ', "")
    actual_name = actual_name.replace(' AP ', "")
    actual_name = actual_name.replace('Expires', "")
    actual_name = actual_name.replace('Name', "")
    actual_name = actual_name.replace('DENONE', "")
    actual_name = actual_name.replace('NONE', "")
    actual_name = actual_name.replace('Address', "")
    actual_name = actual_name.replace('CLASS D', "")
    actual_name = actual_name.replace('CLASSE', "")
    actual_name = actual_name.replace('CLASEXP', "")
    actual_name = actual_name.replace('EXP', "")
    actual_name = actual_name.replace('CLASS', "")
    actual_name = actual_name.replace('ISS', "")
    actual_name = actual_name.replace('SExr', "")
    actual_name = actual_name.replace('Payroll', "")
    actual_name = actual_name.replace('Attn', "")
    actual_name = actual_name.replace('GEXP', "")
    actual_name = actual_name.replace('Class', "")
    actual_name = actual_name.replace('DM', "")
    actual_name = actual_name.replace('Height', "")
    actual_name = actual_name.replace('Expires', "")
    actual_name = actual_name.replace('Expiros', "")
    actual_name = actual_name.replace('Expires', "")
    actual_name = actual_name.replace('VA', "")
    actual_name = actual_name.replace('Name', "")
    actual_name = actual_name.replace('DENONE', "")
    actual_name = actual_name.replace('NONE', "")
    actual_name = actual_name.replace('Address', "")
    actual_name = actual_name.replace('CLASS D', "")
    actual_name = actual_name.replace('CLASSE', "")
    actual_name = actual_name.replace('CLASEXP', "")
    actual_name = actual_name.replace('EXP', "")
    actual_name = actual_name.replace('CLASS', "")
    actual_name = actual_name.replace('Cass', "")
    actual_name = actual_name.replace(' ISS ', "")
    actual_name = actual_name.replace('SExr', "")
    actual_name = actual_name.replace('GEXP', "")
    actual_name = actual_name.replace('ORGAN', "")
    actual_name = actual_name.replace('DONOR', "")
    actual_name = actual_name.replace('DONORJawa', "")
    actual_name = actual_name.replace('DOB', "")
    actual_name = actual_name.replace('ub', "")
    actual_name = actual_name.replace('=', " ")
    actual_name = actual_name.replace(',', " ")
    actual_name = actual_name.replace('@', " ")
    actual_name = actual_name.replace('#', " ")
    actual_name = actual_name.replace('%', " ")
    actual_name = actual_name.replace('^', " ")
    actual_name = actual_name.replace('&', " ")

    actual_name = actual_name.replace('CGA', "")
    actual_name = actual_name.replace('CONG', "")
    actual_name = actual_name.replace('identifier', "")
    actual_name = actual_name.replace('EENHANCED', "")
    actual_name = actual_name.replace(' am ', "")
    actual_name = actual_name.replace(' Mal ', "")
    actual_name = actual_name.replace(' OL ', "")
    actual_name = actual_name.replace('GIN', "")
    actual_name = actual_name.replace('CASS', "")
    actual_name = actual_name.replace(' ADP ', "")
    actual_name = actual_name.replace(' SU ', "")
    actual_name = actual_name.replace('MWAberty', "")
    actual_name = actual_name.replace('FILE', "")
    actual_name = actual_name.replace('Beginning', "")
    actual_name = actual_name.replace('Statement', "")
    actual_name = actual_name.replace('Single', "")
    actual_name = actual_name.replace('Exemptions', "")
    actual_name = actual_name.replace('owances', "")
    actual_name = actual_name.replace('Maso', "")
    actual_name = actual_name.replace('Federa', "")
    actual_name = actual_name.replace(' NY ', "")
    actual_name = re.sub(
        r"(=?EXP|HGT|Earnings|Donor| S |AP |=|,|@|#|%|^|&| E |CGA|CONG|EENHANCED|am|Mal| OL |GIN|CASS C | D |AD | SU |MWAberty|FILE|Beginning|Statement|ll|l |JTD|LICENSE| USA |EYES|DXP|FN|PAYTOTHE|DiP|DIP| IS | TO |THE |ORDER|No |Payro| OC | OF |LN | EN |ADP |Expires|Name|DENONE|NONE|Address|CLASSE|CLASEXP|EXP|ISS|SExr|Payroll|Attn|GEXP|Class|DM|Height|Expiros|Cass|CLASS|ClassE|ORGAN|DONORJawa|DOB|ub|CD)",
        "", actual_name)
    actual_name = re.sub(
        r"\s(=?EXP|HGT|Earnings|Donor|AP |=|,|@|#|%|^|&|CGA|CONG|EENHANCED|am|Mal| OL |GIN|CASS|C |D | AD | SU |MWAberty|FILE|Beginning|Statement|ll|l |JTD|LICENSE|USA |EYES|DXP|FN|PAYTOTHE|DiP|DIP|IS | TO |THE |ORDER|No |Payro| OC | OF |LN |EN |ADP |Expires|Name|DENONE|NONE|Address|CLASSE|CLASEXP|EXP|ISS|SExr|Payroll|Attn|GEXP|Class|DM|Height|Expiros|Cass|CLASS|ClassE|ORGAN|DONORJawa|DOB|ub|CD)",
        "", actual_name)
    return actual_name

